version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user -e .[dev,sphinx]


      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip
      # Run tests
      - run:
          name: Run tests
          command: |
            pytest --cov=download
            codecov

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html

      - store_artifacts:
          path: doc/_build/html/
          destination: html

      - add_ssh_keys:
          fingerprints:
            # The SSH key fingerprint
            - "7d:04:9c:2d:bf:00:74:43:47:7d:5d:ad:53:49:2a:5b"
      - run:
          name: Deploy documentation on master
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]
            then
            pip install ghp-import
            ghp-import doc/_build/html -n -p -f
            fi


workflows:
  version: 2
  default:
    jobs:
      - tests
